name: ranna_app
description: বাংলাদেশ ও বিশ্বের রেসিপি অ্যাপ
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  get:
  google_fonts:
  equatable:
  flutter_screenutil:
  shared_preferences:
  url_launcher:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true