name: Ranna
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  get:
  google_fonts:
  equatable:
  flutter_screenutil:
  shared_preferences:
  url_launcher:
  google_mobile_ads:
  flutter_launcher_icons:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/foreground_white.png"
  adaptive_icon_foreground: "assets/foreground_white.png"
  adaptive_icon_background: "#F44336"